#!/usr/bin/env bash
[ -f "$HOME/.zplug/init.zsh" ] && source "$HOME/.zplug/init.zsh"

# Navigation Options
setopt AUTO_CD                                  # Go to folder path without using cd.
setopt AUTO_PUSHD                               # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS                        # Do not store duplicates in the stack.
setopt PUSHD_SILENT                             # Do not print the directory stack after pushd or popd.
setopt CORRECT                                  # Spelling correction
setopt CDABLE_VARS                              # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB                            # Use extended globbing syntax.
setopt INTERACTIVE_COMMENTS                     # Allow comments even in interactive shells.

# History Options
setopt EXTENDED_HISTORY                         # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY                            # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST                   # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS                         # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS                     # Delete an old recorded event if a new event is a duplicate.
setopt HIST_IGNORE_SPACE                        # Do not record an event starting with a space.
setopt HIST_FIND_NO_DUPS                        # Do not display a previously found event.
setopt HIST_SAVE_NO_DUPS                        # Do not write a duplicate event to the history file.
setopt HIST_VERIFY                              # Do not execute immediately upon history expansion.

# Increase history size
HISTFILE="$ZDOTDIR/.zhistory"                   # History filepath
HISTSIZE=10000                                  # Maximum events for internal history
SAVEHIST=10000                                  # Maximum events in history file
HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"  # Ignore the most common commands in history

# Setup asdf
source $ASDF_DIR/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)

autoload -U colors && colors
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Aliases
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/exports.zsh

# Plugins (loaded with zplug)
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "plugins/web-search", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# Starship Prompt
eval "$(starship init zsh)"
